#ifndef PROCESSION_UTIL_H
#define PROCESSION_UTIL_H

#include <Arduino.h>


namespace ProcessionUtil {
  /**
   * @brief Given an incoming message from Procession, process it for ease of use.
   */
  String processProcessionMessage(String message);

  /**
   * @brief Parse a "topic=value" string.
   *
   * @param message  The incoming string to parse. It may be passed by reference or copy –
   *                 the function does not modify it.
   * @param topic    Output parameter – will contain everything before the first '='.
   * @param value    Output parameter – will contain everything after the first '=', trimmed
   *                 of leading/trailing whitespace (optional, can be removed if you don't want it).
   *
   * @return true  If a single '=' was found and both parts are non‑empty.
   * @return false If the string does not contain '=', or if either side is empty.
   *
   * Note: generated by openai/gpt-oss-120b on 2025 09 24.
   */
  bool parseTopicValue(const String &message, String &topic, String &value);

  /**
   * @brief A utility for helping add a debounce behavior to hardware events.
   */
  class Debouncer {
  public:
    int debounceTime;

    unsigned long lastDebounceTime;
    unsigned long currentTime;
    unsigned long diff;

    Debouncer()
      : debounceTime(75), lastDebounceTime(0), currentTime(0), diff(0) {
    }
    Debouncer(int time)
      : debounceTime(time), lastDebounceTime(0), currentTime(0), diff(0) {
    }

    void reset () {
      lastDebounceTime = millis();
    }

    bool ready () {
      diff = millis() - lastDebounceTime;
      return diff >= debounceTime;
    }
  };
}

#endif // PROCESSION_UTIL_H
