#include "ProcessionUtil.h"
#include <Arduino.h>


String ProcessionUtil::processProcessionMessage(String message) {
  message.trim();

  if (message.length() == 0) {
    return String();
  }

  int start = 0;
  int end = message.length();

  // remove "data." from the start
  if (message.startsWith("data.")) {
    start += 5;
  }

  return message.substring(start, end);
}

/**
 * Note: generated by openai/gpt-oss-120b on 2025 09 24.
 */
bool ProcessionUtil::parseTopicValue(const String &message, String &topic, String &value)
{
  // Find the position of the first '=' character
  int eqPos = message.indexOf('=');

  // No equal sign → malformed input
  if (eqPos == -1) {
    return false;
  }

  // Extract the substrings
  topic = message.substring(0, eqPos);
  value = message.substring(eqPos + 1);   // everything after '='

  // Optional: trim whitespace from both sides (Arduino String has a trim() method)
  topic.trim();
  value.trim();

  // Consider empty topic or value as an error – adjust to your needs
  if (topic.length() == 0 || value.length() == 0) {
    return false;
  }

  return true;   // success
}
